#!/usr/bin/env php
<?php

if ($argc > 1 && $argv[1] === 'config') {
  print('graph_title Upstream power levels'.PHP_EOL);
  print('graph_vlabel power level (dBmV)'.PHP_EOL);
  print('graph_category superhub'.PHP_EOL);
  print('graph_scale no'.PHP_EOL);

  for ($i = 1; $i <= 4; ++$i) {
    print('us'.$i.'.label US-'.$i.PHP_EOL);
    print('us'.$i.'.warning 31:54'.PHP_EOL);
    print('us'.$i.'.critical 31:55'.PHP_EOL);
  }

  exit();
}

$document = new DOMDocument();
$document->loadHTMLFile('http://'.getenv('host').'/cgi-bin/VmRouterStatusUpstreamCfgCgi', LIBXML_NONET);

$query = new DOMXPath($document);

$nodes = $query->evaluate('//td[../td[@class="title"]="Power Level (dBmV)" and not(@class)]/text()');

$i = 0;
foreach ($nodes as $node) {
  $value = $node->textContent;
  if ($value === 'N/A') {
    $value = 'U';
  }

  print('us'.++$i.'.value '.$value.PHP_EOL);
}

